### ISSUE TITLE
Processing system-sledovani-shody-a-interni-audit fails due null pointer exception

### ISSUE THREAD

**Issue by blcham** [kbss-cvut/bpmn2stamp#57]
Command:
```
cd bpmn-convertor-examples/processes/ucl
./bin/process-bpmn.sh bpmn/system-sledovani-shody-a-interni-audit.bpmn
```

Returns error:
```
Converting BBO file 'system-sledovani-shody-a-interni-audit-bpmn.ttl' to STAMP file 'system-sledovani-shody-a-interni-audit-pre-stamp.ttl'
Exception in thread "main" java.lang.NullPointerException: uri cannot be null
        at org.semanticweb.owlapi.util.OWLAPIPreconditions.checkNotNull(OWLAPIPreconditions.java:102)
        at org.semanticweb.owlapi.model.IRI.create(IRI.java:150)
```

Full log: 
[system-sledovani-shody-a-interni-audit.log](https://github.com/kbss-cvut/bpmn2stamp/files/11174475/system-sledovani-shody-a-interni-audit.log)

**Comment by blcham** [comment]
Blocked by https://github.com/kbss-cvut/jopa/issues/167

**Comment by grigobog** [comment]
Should be fixed with new JOPA release https://github.com/kbss-cvut/jopa/releases/tag/v0.22.1
